Add signup file
DevGrowth/house_inventory pull request #2
Opened 2023-10-15 16:24 UTC by Ivandro-Alfredo

The initial repository didn't have any documents for the web page.
As it is an open project and requires the insertion of data and subsequent manipulation, I suggest that you register your users in order to ensure greater control over each user's data.
@aosccode

2023-10-15 19:34 UTC, gquende requested changes

2023-10-15 19:34 UTC, gquende commented on backend/src/sinup.js
The project must follow an MVC architecture, as it scales it will change architecture to Clean Architecture

2023-10-15 19:34 UTC, gquende commented on backend/src/sinup.js
Therefore, separate this logic by creating a user model which will contain the user's primary data such as name, surname, password, email. And a controller called AuthController where it will contain all functions related to authentication

2023-10-15 19:34 UTC, gquende commented on backend/src/sinupValidation.js
The project must follow an MVC architecture, as it scales it will change architecture to Clean Architecture. Therefore, separate this logic by creating a user model which will contain the user's primary data such as name, surname, password, email. And a controller called AuthController where it will contain all functions related to authentication

2023-10-18 11:21 UTC, Ivandro-Alfredo commented on backend/src/sinup.js
ok, I'll follow the instructions.

2023-10-18 12:30 UTC, Ivandro-Alfredo commented on backend/src/sinup.js
If This problem was solved, and if  it's just ok let me know.

2023-10-18 13:12 UTC, Ivandro-Alfredo reviewed
Refactoring the code, hope it's helps.

2023-10-21 18:34 UTC, gquende commented on backend/src/sinup.js
Done!

2023-10-21 18:49 UTC, gquende approved these changes

2023-10-21 18:50 UTC, merged